services:
  app:
    volumes:
      - ./:/app
      - /app/node_modules

  llm-server:
    ports:
      - "8081:8081"

  python-rag:
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8090", "--reload"]
    volumes:
      - ./python-services/rag:/app

  python-stt:
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8091", "--reload"]
    volumes:
      - ./python-services/speach-to-text:/app
    ports:
      - "8091:8091"